### ISSUE TITLE
Can't boot

### ISSUE THREAD

**Issue by jjdredd** [kholia/OSX-KVM#10]
I'm following the instructions with the magic boot line in the readme and boot.sh but i'm still stuck on the boot screen 
![1](https://cloud.githubusercontent.com/assets/4748239/18772977/1940c8d0-8108-11e6-900c-ecec61cbd2e6.png)

**Comment by jjdredd** [comment]
the image is `Install_OS_X_10.11.6_El_Capitan.iso` from the MEGA link in the readme

**Comment by kholia** [comment]
What happens when you press the Enter button on the keyboard? Have you followed steps mentioned in the `Debugging` section of https://github.com/kholia/OSX-KVM/blob/master/README.md file?

**Comment by ProxyChain** [comment]
Same thing here on Debian Jessie with QEMU 2.5 - typing out the `-v "KernelBooter_kexts"="Yes" "CsrActiveConfig"="103"` flags into Enoch and pressing enter seems to just clear the prompt back to the screenshot @jjdredd posted.

Have tried just `-v` by itself, just pressing enter with no arguments; tried both the suggestions in the debugging section too.

**Comment by kholia** [comment]
Which CPU are you running? Is it an Intel processor?

Is VT-x enabled on your host machine (run `grep vmx /proc/cpuinfo` to check)?

What does running `cat /sys/module/kvm/parameters/ignore_msrs` show?

**Comment by julianscheel** [comment]
Same problem here, AMD FX-8350 host processor.

```
> cat /proc/cpuinfo
processor       : 0
vendor_id       : AuthenticAMD
cpu family      : 21
model           : 2
model name      : AMD FX(tm)-8350 Eight-Core Processor
stepping        : 0
microcode       : 0x600084f
cpu MHz         : 1400.000
cache size      : 2048 KB
physical id     : 0
siblings        : 8
core id         : 0
cpu cores       : 4
apicid          : 16
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext
 fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc extd_apicid aperfmperf eagerfpu pni pclmulqdq monitor ssse3 fma cx16
sse4_1 sse4_2 popcnt aes xsave avx f16c lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs xop skini
t wdt lwp fma4 tce nodeid_msr tbm topoext perfctr_core perfctr_nb cpb hw_pstate vmmcall bmi1 arat npt lbrv svm_lock nrip_save tsc_scale
vmcb_clean flushbyasid decodeassists pausefilter pfthreshold
bugs            : fxsave_leak sysret_ss_attrs null_seg
bogomips        : 8003.98
TLB size        : 1536 4K pages
clflush size    : 64
cache_alignment : 64
address sizes   : 48 bits physical, 48 bits virtual
power management: ts ttp tm 100mhzsteps hwpstate cpb eff_freq_ro

[...]
```

**Comment by ProxyChain** [comment]
![image](https://cloud.githubusercontent.com/assets/4223195/18790721/efe81798-8203-11e6-8871-6ac5296217b5.png)

`grep vmx /proc/cpuinfo` returns matches for the `vmx` flag on my i5-4570, so VT-x is enabled

**Comment by kholia** [comment]
@julianscheel I don't know if AMD processors are supported (I am guessing not). I don't have an AMD processor to try this.

**Comment by kholia** [comment]
@ProxyChain I am out of new debugging ideas for now. Maybe try a different host operating system like Fedora 24 64-bit. The SeaBIOS version on Debian Jessie seems to be older than the one shipped with Fedora 24. This tip might or might not work.

**Comment by kholia** [comment]
The SeaBIOS version in Debian Jessie seems to be OK, bummer.

**Comment by julianscheel** [comment]
It appears one has to set the cpu vendor explicitly to GenuineIntel on AMD hosts. Just have to figure out how to do that with virt-manager...

**Comment by MMI** [comment]
Same thing here on Ubuntu 16.04.1 LTS with QEMU 2.5.
CPU:
```
root@ares:~/OSX-KVM# cat /proc/cpuinfo 
processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 63
model name	: Intel(R) Core(TM) i7-5930K CPU @ 3.50GHz
...
```
The suggestions in the Debugging section don't seem to do anything.

:(

**Comment by charuruflex** [comment]
I had the same issue with virt-manager. Using boot-macOS.sh resolved it, I can boot now but I can't explain why it's working.

**Comment by jjdredd** [comment]
>  What happens when you press the Enter button on the keyboard?

it falls back to my screenshot

> Have you followed steps mentioned in the Debugging section of https://github.com/kholia/OSX-KVM/blob/master/README.md file?

I have tried `echo 1 > /sys/module/kvm/parameters/ignore_msrs` and
`"KernelBooter_kexts"="Yes" "CsrActiveConfig"="103"`

vmx is there

`processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 94
model name	: Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
stepping	: 3
microcode	: 0x76
cpu MHz		: 2500.000
cache size	: 6144 KB
physical id	: 0
siblings	: 8
core id		: 0
cpu cores	: 4
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 22
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch ida arat epb pln pts dtherm hwp hwp_notify hwp_act_window hwp_epp intel_pt tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx rdseed adx smap clflushopt xsaveopt xsavec xgetbv1
bugs		:
bogomips	: 5183.92
clflush size	: 64
cache_alignment	: 64
address sizes	: 39 bits physical, 48 bits virtual
power management:
`

**Comment by hobarrera** [comment]
I'm having the exact same issue, though I'm using an Intel CPU (this is a 2013 MacBook Air):

```
$ cat /sys/module/kvm/parameters/ignore_msrs
Y
$ lscpu
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                4
On-line CPU(s) list:   0-3
Thread(s) per core:    2
Core(s) per socket:    2
Socket(s):             1
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 69
Model name:            Intel(R) Core(TM) i5-4250U CPU @ 1.30GHz
Stepping:              1
CPU MHz:               2458.380
CPU max MHz:           2600.0000
CPU min MHz:           800.0000
BogoMIPS:              3801.03
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              3072K
NUMA node0 CPU(s):     0-3
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm epb tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid xsaveopt dtherm ida arat pln pts
```

Running `"KernelBooter_kexts"="Yes" "CsrActiveConfig"="103"` does nothing.

**Comment by kholia** [comment]
You may need to clone the repository again to get the latest changes.

**Comment by kholia** [comment]
I have updated https://github.com/kholia/OSX-KVM/blob/master/README.md and the virt-manger method should be working too now.

**Comment by julianscheel** [comment]
Thanks for the update, new virt-manager config fails on AMD cpu with this error:
```
libvirtError: unsupported configuration: guest and host CPU are not compatible: host CPU vendor does not match required CPU vendor Intel
```

**Comment by kholia** [comment]
@julianscheel I believe that AMD CPU are not supported by macOS without kernel patches. Can you try the `boot-macOS.sh` script instead of virt-manager? I am curios to know what happens then.

**Comment by hobarrera** [comment]
> the virt-manger method should be working too now.

What's changed for the virt-manager method?

**Comment by kholia** [comment]
The virt-manager method now defines a CDROM device correctly and also has an updated CPU model value.

**Comment by jjdredd** [comment]
the `boot-macOS.sh` gives the same result

**Comment by kholia** [comment]
Changing "-m 8192" to "-m 2048" in boot-macOS.sh works fine here. QEMU 2.5.1 should be OK too. `

**Comment by julianscheel** [comment]
@kholia Using boot-macOS.sh I can actually start the installation. Trying to install now.

**Comment by kholia** [comment]
@julianscheel How did the installation go? Are you still using AMD FX-8350 processor for doing this?

**Comment by julianscheel** [comment]
@kholia Yes, still on the AMD. Installation went smooth. Right now network is not working, but I assume I need to do some configuration on my host for the tap0 device to work as expected by qemu...

**Comment by kholia** [comment]
@julianscheel https://github.com/kholia/OSX-KVM/blob/master/networking-qemu-kvm-howto.txt has some notes on getting the network to work.

**Comment by julianscheel** [comment]
@kholia Wouldn't `virbr0` need to be assigned to a physical device (for example `eth0`) as well to actually have `tap0` connected to a network?

**Comment by kholia** [comment]
@julianscheel Installing the "virt-manager" package automagically creates a suitable "virbr0" local bridge. I use this method to enable networking in guest VMs.

**Comment by jjdredd** [comment]
@julianscheel can you write step by step how you managed to boot?

**Comment by julianscheel** [comment]
@jjdredd In fact it just works with boot-macOS.sh from this repository as it is now. All required changed have been merged in there.
And don't forget to do `echo 1 > /sys/module/kvm/parameters/ignore_msrs` first, as noted in the head of that script.

**Comment by julianscheel** [comment]
@kholia Using virt-manager works as well after removing `<vendor>Intel</vendor>` from cpu section in the xml file. Only the `<qemu:arg value='Penryn,vendor=GenuineIntel'/>` is needed to make it work with AMD CPU.
Network works as well using virt-manager now.

Next task will be GPU passthrough :)

**Comment by kholia** [comment]
@julianscheel Thanks for the update. I have updated `macOS-libvirt.xml` accordingly now. 

Even after all these changes, my old AMD Phenom II X3 720 processor does not work (probably due to missing some SSE instruction set).

**Comment by jjdredd** [comment]
Still the same problem here.

**Comment by jjdredd** [comment]
Any ideas how to debug further?

**Comment by thenickdude** [comment]
Same problem here, QEMU 2.6.1 on Debian Jessie (Proxmox), Intel CPU with VT-x enabled.

I noticed that this behaviour (pressing enter clears the line and does nothing) was the same whether there was a CD mounted or not, so I figured the problem was likely down to the CD not being read at all. I compared the broken KVM launch command that Proxmox was generating against boot-macOS.sh, which works. For me the problem was here in the device entries Proxmox generated for the mounted CD:

```
-drive 'file=/var/lib/vz/template/iso/sierra.iso,if=none,id=drive-ide0,media=cdrom,aio=threads'
-device 'ide-cd,bus=ide.0,unit=0,drive=drive-ide0,id=ide0,bootindex=100'
```

By changing the device from "ide-cd" to "ide-drive" and removing the "media=cdrom" clause, it boots past the bootloader stage!

```
-drive 'file=/var/lib/vz/template/iso/sierra.iso,if=none,id=drive-ide0,aio=threads'
-device 'ide-drive,bus=ide.0,unit=0,drive=drive-ide0,id=ide0,bootindex=100'
```

It turns out that all I needed to do was edit my VM configuration file to remove the "media=cdrom" clause. So my complete Proxmox /etc/pve/qemu-server/100.conf file now looks like this:

```
args: -device isa-applesmc,osk="osk-here-is-inserted-here-in-my-real-conf" -smbios type=2 -kernel /var/lib/vz/template/qemu/enoch_rev2839_boot -cpu Penryn,kvm=off,vendor=GenuineIntel
boot: dcn
bootdisk: ide0
cores: 4
cpu: Penryn,hidden=1
ide0: local:iso/sierra.iso,size=6074010K
ide2: local-lvm:vm-100-disk-1,size=32G
keyboard: en-us
machine: pc-q35-2.4
memory: 8096
name: sierra
net0: e1000=DE:AD:BE:EF:D6:90,bridge=vmbr0
numa: 0
ostype: other
scsihw: virtio-scsi-pci
smbios1: uuid=30c90ff2-50e9-442d-86b2-52d833b91294
sockets: 1
tablet: 0
vga: std
```

**Comment by jjdredd** [comment]
@thenickdude everything seems to be ok in boot-macOS.sh according to your notes, but it still doesn't work.

**Comment by kholia** [comment]
I am closing this issue due to lack of more debugging steps / tips.

**Comment by jjdredd** [comment]
Why close? Why not have it as warning for other users and to prevent them from  reporting duplicate bugs?
