### ISSUE TITLE
Screen tearing and sluggish experience

### ISSUE THREAD

**Issue by iostreamer-X** [kholia/OSX-KVM#12]
First of all, thank you so much for this.

I opted for the ./boot-macOS.sh approach and with the help of your troubleshooting guide, I was able to get it working.
Next I got the network up and changed the res to 1920x1080x32.

I would be very grateful if you could point out anything to overcome the sluggish nature. Everything just tears up and is kinda slow(high res problem probably?)

Specs might help:
```
vendor_id	: GenuineIntel
cpu family	: 6
model		: 94
model name	: Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz
stepping	: 3
microcode	: 0x84
cpu MHz		: 1108.582
cache size	: 6144 KB
physical id	: 0
siblings	: 4
core id		: 0
cpu cores	: 4
```

Thanks again!

**Comment by kholia** [comment]
This lack of video acceleration in the guest OS seems to be a known problem. Getting accelerated video working is possible but it involves substantially more work. See "GPU Passthrough" section in [this guide](https://macosxvirtualmachinekvm.wordpress.com/guide-mac-os-x-10-11-el-capitan-vm-on-unraid/). Also [this blog](http://vfio.blogspot.in/) should be helpful. I believe that this approach requires a PC with a spare video card.

The other option is to enable "Screen Sharing" in the guest OS and then use a VNC client from the host OS to connect to the guest.

**Comment by iostreamer-X** [comment]
Thanks!
