### ISSUE TITLE
Permission problem

### ISSUE THREAD

**Issue by hellas2000** [kholia/OSX-KVM#13]
I followed the instructions, but when started the VM in virt-manager, there is an error :
Error starting domain: internal error: process exited while connecting to monitor: 2016-09-26T06:58:18.376948Z qemu-system-x86_64: -drive id=MacDVD,if=none,snapshot=on,file=/home/xxx/downloads/OSX-KVM-master/Install_macOS_Sierra_(OS_X_10.12).iso: Could not open '/home/xxx/downloads/OSX-KVM-master/Install_macOS_Sierra_(OS_X_10.12).iso': Permission denied

I'm using Ubuntu1604 on on i5-4460 CPU.
virt-manager 1.3.2
qemu-kvm 2.5

I have gave the iso file 777 permission, but won't help, any ideas?

**Comment by kholia** [comment]
I have run into this problem in the past but I don't remember how I fixed it.

Maybe https://github.com/jedi4ever/veewee/issues/996 (or Googling) can help.

Try using the `boot-macOS.sh` method if virt-manager keeps causing problems.

Please post back your solution here, thanks.

**Comment by hellas2000** [comment]
tried method in jedi4ever/veewee#996, no luck.

then try to use boot-macOS.sh, I executed
sudo echo 1 > /sys/module/kvm/parameters/ignore_msrs
I got an error
Permission denied

could this be the reason?

**Comment by kholia** [comment]
Try running `echo 1 | sudo tee /sys/module/kvm/parameters/ignore_msrs`.

**Comment by kholia** [comment]
Please note that I cannot provide further end-user support. Basic Linux troubleshooting knowledge is required to get this project working.

**Comment by rmoriz** [comment]
In my case this was caused by strict apparmor rules, see syslog (Ubuntu 16.04)

**Comment by MMI** [comment]
@rmoriz I seem to be running into this too. May I ask, how did you relax the rules?

**Comment by MMI** [comment]
I had two problems. One is that my VM files are on separate volume in a non-standard path _and_ the XML file defines all the devices in a way that the apparmor files don't get created right (the symptom is that the ISO cannot be opened with permission denied). My solution was to change the apparmor libvirt template file to allow access to my non-standard path.

The second symptom was that libvirt could not "get temp file". Seems that the XML file has `snapshot=on` which seems to cause libvirt to want to make a file in /var/tmp but the apparmor rules for libvirt deny access...  I changed the XML to `snapshot=off`

After these changes, I was able to boot the installer. w00t!

**Comment by zhangyz189** [comment]
Ubuntu 16.04
I am very lazy，so I only modify the file。
/etc/libvirt/qemu.conf
security_driver = "none"

**Comment by shehzan10** [comment]
To add my two cents here, I tried the solutions that worked for other users but they all failed. I was using the xml file to create the KVM. Eventually I decided to remove the last 4 lines of the `qemu:arg` which define the setup for the ISO.
After doing this, I manually mounted the ISO as a disk drive with SATA interface.
And that made it work.
