### ISSUE TITLE
Install macOS Sierra.app

### ISSUE THREAD

**Issue by Teepareep** [kholia/OSX-KVM#16]
The Sierra installer is called `Install macOS Sierra.app` in /Applications and the create iso script isn't designed with this in mind.

```
Looking for downloaded OS upgrades... ls: /Applications/Install OS X *.app/: No such file or directory
Error: Can't find downloaded OS X upgrade
```

I tried manually adjusting it and now get 

```
Looking for downloaded OS upgrades... found
Using "/Applications/Install macOS Sierra.app".
Detecting OS X name for installation... macOS Sierra
Creating temporary directory... succeed
Mounting InstallESD.dmg...
hdiutil: attach failed - Resource busy
Error: Can't mount installation image
Removing temporary files...
```

It's unclear if this second issue is still caused by the file names.

**Comment by kholia** [comment]
The ISO creation script already has support for macOS Sierra. See the following code snippet,

```
stage_start "Looking for downloaded OS upgrades"
unset test_name || exit_with_error
IFS=$'\n'
dirlist=(`ls -d1 /Applications/Install\ {OS\ X,macOS}\ *.app`)
IFS="$save_IFS"
[[ ${#dirlist[@]} -eq 0 ]] && exit_with_error "Can't find downloaded OS X upgrade"
```

Try a fresh clone of this repository if you don't see this code in your ISO creation script. The first error message "No such file or directory" should be harmless, I think. What manual adjustments did you make to get the script moving ahead?

To fix the "hdiutil: attach failed - Resource busy" message, try umounting the macOS Sierra installer, and wait for a bit.

**Comment by kholia** [comment]
Also see the "Debugging" section in https://github.com/kholia/OSX-KVM/blob/master/README.md file.

**Comment by Teepareep** [comment]
Good call on unmounting it. It doesn't show up as mounted in Finder on El Capitan, but it was available to unmount with Disk Utility. 

I realize the issue was that I downloaded the script attributed from the k2k-OSX-Tools repo instead of grabbing your modified version with the Sierra functionality.
