### ISSUE TITLE
GNU mktemp: fails to create temporary directory

### ISSUE THREAD

**Issue by pjmeyer** [kholia/OSX-KVM#18]
Found on:
 - macOS Sierra 10.12
 - mktemp (GNU coreutils) 8.25

If a recent version of mktemp is installed (typically if GNU coreutils has been installed via homebrew), mktemp will fail if the template string doesn't contain enough consecutive "X"s at the end. This causes the following error when running the ISO creation script:
`Creating temporary directory... mktemp: too few X's in template ‘osx_iso_tmpdir’`

Additional context from `man mktemp`:
```
Create  a  temporary  file or directory, safely, and print its name.  TEMPLATE must contain at least 3 consecutive 'X's in last component.
```

**Comment by kholia** [comment]
The PR for this fixing this issue has been merged now. Hence, closing this issue.
