### ISSUE TITLE
TIP: El Capitan has native support for vmxnet3 network device

### ISSUE THREAD

**Issue by elpetak** [kholia/OSX-KVM#2]
El Capitan has native support for vmxnet3 network device.
I don't know if it's as stable as the e1000 one, but in theory it should perform better.

**Comment by kholia** [comment]
Thanks, I will give it a go soonish.

**Comment by rflagler** [comment]
I tried this and the driver works almost perfectly. I had issues with both the e1000 and virtio network adapters but the vmxnet3 just seems to work. There is one issue I noticed though, and for some reason using this network adapter, Screen Sharing doesn't seem to work. Anyone encountered that?

**Comment by kholia** [comment]
I will add this tip to the documentation later.
