### ISSUE TITLE
Does not work for macOS Sierra

### ISSUE THREAD

**Issue by AntonTrapp** [kholia/OSX-KVM#20]
Error: Can't find downloaded OS X upgrade

Working fine for El Capitan. Tnx!

**Comment by AntonTrapp** [comment]
Actually they renamed the files so the test_name does not match, a parameter for the filename would be nice.

**Comment by kholia** [comment]
Are you using the `create_install_iso.sh` script from this repository? 

It works just fine for macOS Sierra (confirmed by multiple folks).

**Comment by AntonTrapp** [comment]
Hi. Try it in Germany, Austria, Swizerland, ... ;) - the name until El Capitan was "Installieren ..." now it is "macOS ... installieren". Think that many non english languages will have the same problem. It's simple to rename in the script (if the user has enough skills) but an optional parameter would be nice for those wo run sudo scripts and don't understand what they are doing :D

btw, tnx for the detailled information here!

**Comment by kholia** [comment]
Aha, I see the problem now. It seems that the script already supports specifying the OS X / macOS installation app path.

```
$ cat create_install_iso.sh
...
Valid options are:
      -a, --app[lication] <OS X Install app>
                   Path and name of OS X upgrade application.
                   Path can be omitted if application is located at
                   default path.
```

Can you try this `-a` option and report back if it works? Thanks.

**Comment by kholia** [comment]
Example,

```
$ sudo ./create_install_iso.sh -a /Applications/Install\ macOS\ Sierra.app/
```

**Comment by AntonTrapp** [comment]
Perfect! I am too much used in just opening my Sublime editor and searching for the error message and fixing the script instead of looking for its parameters :D

The -a parameter is working fine. So the only thing I would change: the error message (please use -a if ...).

**Comment by kholia** [comment]
I have added a note regarding this to the README.md file. I have also changed the error message in the script. Thanks!

**Comment by AntonTrapp** [comment]
Thanks for all the good work!!!
