### ISSUE TITLE
Can't find boot file: /System/Library/Kernels/kernel

### ISSUE THREAD

**Issue by TheDharc** [kholia/OSX-KVM#21]
Hey, I'm following the README but I stuck in the message 'Can't find boot file: /System/Library/Kernels/kernel'.
Any idea? Using Linux Mint 18 here.

**Comment by kholia** [comment]
How did you generate the installation ISO image? Did you use the `create_install_iso.sh` script from this repository to do so?

**Comment by TheDharc** [comment]
No, I don't have a Mac, so i downloaded here https://plus.google.com/+SysAdminsHowtos/posts/6e98eRghsw1

**Comment by kholia** [comment]
I don't understand why you reported a "bug" against some third-party ISO image here. You mentioned reading the README file but you didn't follow what is written there at all. I find such bug reports unfair and annoying.

Try http://bit.do/bootable for some working ISO images.

**Comment by aaronorosen** [comment]
Any chance you could post another link with a valid iso that uses google drive or something else that doesn't have a download limit? I'm not able to download those files since they only let you download 5 gigs worth and then have to pay :(

**Comment by kholia** [comment]
I don't have the bandwidth to do so.

**Comment by TheDharc** [comment]
@aaronorosen Tor Browser is your friend.
