### ISSUE TITLE
No SMBIOS replacement found.

### ISSUE THREAD

**Issue by TheDharc** [kholia/OSX-KVM#22]
I can't boot. Stuck in this problem:
![screenshot_20161011_012238](https://cloud.githubusercontent.com/assets/3090967/19258911/fbc5a45c-8f52-11e6-8345-0be92129a515.png)

**Comment by kholia** [comment]
I haven't seen this problem. Have you tried the debugging tips mentioned in the README.md file?

Which host CPU and OS are you trying this on? Is VT-x enabled?

**Comment by Joseph14078** [comment]
Running into a similar issue. VM stalls for a second here and then bootloops. Using `./boot-macOS.sh`, but also happens with libvirt.

![spectacle s21457](https://cloud.githubusercontent.com/assets/4339897/19285778/5a56fe1e-8fc9-11e6-86b8-d917011b5f4e.png)

My specs:
* Manjaro Linux 16.06.1 x64 (Kernel 4.4.24-1-MANJARO) (Arch based)
* QEMU emulator version 2.7.0
* 12GB RAM (4GB allocated to VM)
* Intel i5-4690k
* UEFI (On host)
* Gigabyte B85M-DS3H-A mobo

I'm wondering if it's a version difference with QEMU/KVM. I had to roll back VirtualBox from 5.x to 4.3 to get OS X Yosemite to install on it.

**Comment by TheDharc** [comment]
Well, my QEMU is 2.5, so I don't believe it's a regression. All my virtualization features are enabled in BIOS. I think it's a hardware problem, I can't see other reason.

**Comment by Joseph14078** [comment]
Found my solution!
> As of Yosemite (OS X 10.10), on kernels older than 4.7, we need to tell KVM to ignore unhandled MSR accesses (During boot, Yosemite attempts to read from MSR 0x199, which is related to CPU frequency scaling, and is clearly not applicable to a VM guest):
> `echo 1 > /sys/module/kvm/parameters/ignore_msrs`
Source: http://www.contrib.andrew.cmu.edu/~somlo/OSXKVM/

**Comment by TheDharc** [comment]
That does not worked for me, but I installed the latest kernel and then now works.

Do you know if it's possible make pcipassthru with my Nvidia GeForce?

**Comment by kholia** [comment]
@TheDharc It's great to hear that things are working now. Which host OS and kernel are you using now? This information will be useful to other folks who are having problems.

See https://wiki.archlinux.org/index.php/PCI_passthrough_via_OVMF for GPU passthrough. I haven't tried it myself.

**Comment by TheDharc** [comment]
I'm on Linux Mint 18, installed Linux 4.8.1 now.

Thanks for the link.
