### ISSUE TITLE
Create a modern architecture VM

### ISSUE THREAD

**Issue by jetlabme** [kholia/OSX-KVM#23]
Hi guys. Thank you for you work.
I read the boot.sh and maco_boot.sh and, if i'm right, you're virtualising a quite old machine based on core2duo and 35 chipset, maybe i'm wrong. I'm quite new to KVM, so can you help me or provide a setup for newer xeon or core i7 chips?

**Comment by kholia** [comment]
This old setup (core2duo, 35 chipset) has been tested well to work for latest Apple operating systems. You are free to experiment on your own with newer processor / chipset models.
