### ISSUE TITLE
After reboot physical machine, virtual machine don't start

### ISSUE THREAD

**Issue by voxsoftware** [kholia/OSX-KVM#24]
I can do the process correctly, install the os, install programas, restart virtual machine, all ok. But if i restart the physical machine, the virtual machine don't start. 

Before install osx in virtual machine, I have to edit the qemu.conf, uncommented the lines 
user="root"
group="root"
Also add a line
"security"="none"

Maybe this edit could affect the virtual machine behavior. 

If I restart again my physical machine, the problem continue, i cannot start the virtual machine. If I delete the virtual machine, and I create a new same as before reboot, don't start too

*Correction, the virtual machine start, but don't boot, 
before load the operating system the virtual machine automatically reboot*

**My OS**: Ubuntu 16.04 64 bits

**Comment by kholia** [comment]
After the reboot, are you doing "echo 1 > /sys/module/kvm/parameters/ignore_msrs"?

**Comment by voxsoftware** [comment]
These command don't work, I have to put:
echo 1 > sudo /sys/module/kvm/parameters/ignore_msrs

**Comment by kholia** [comment]
Try `echo 1 | sudo tee /sys/module/kvm/parameters/ignore_msrs` instead.

Please note that I can't provide further basic end-user support.

**Comment by voxsoftware** [comment]
Ok one moment please, I will test

**Comment by voxsoftware** [comment]
The command echo 1 > sudo /sys/module/kvm/parameters/ignore_msrs I executed, but i will test the other

**Comment by voxsoftware** [comment]
Ok, thanks the command **echo 1 | sudo tee /sys/module/kvm/parameters/ignore_msrs** work for me.
