### ISSUE TITLE
create_install_iso.sh: Error: Can't mount installation image

### ISSUE THREAD

**Issue by iheijoushin** [kholia/OSX-KVM#25]
When running create_install_iso.sh on my Mac running 10.12 (16A323):
`Olivia:~ XXX$ sudo /Users/XXX/Desktop/OSX-KVM-master/create_install_iso.sh`

I get the following output and error:
`Olivia:~ XXX$ sudo /Users/XXX/Desktop/OSX-KVM-master/create_install_iso.sh
Looking for downloaded OS upgrades... found
Using "/Applications/Install macOS Sierra.app".
Detecting OS X name for installation... macOS Sierra
Creating temporary directory... succeed
Mounting InstallESD.dmg... 
**hdiutil: attach failed - Resource busy
Error: Can't mount installation image**
Removing temporary files...`

How can I resolve this issue? Thanks so much for your assistance.

**Comment by kholia** [comment]
The fix is already well described in the https://github.com/kholia/OSX-KVM/blob/master/README.md file. 

Please read it carefully.

**Comment by iheijoushin** [comment]
I guess I didn't read it carefully the first time! Thanks so much for pointing out the debugging section I clearly missed the first time!
