### ISSUE TITLE
processing error - resetting ehci HC

### ISSUE THREAD

**Issue by LLCF** [kholia/OSX-KVM#27]
When Ｉ　run
sudo ./boot-macOS.sh
I will get
```
(qemu) ehci warning: guest requested more bytes than allowed
processing error - resetting ehci HC
ehci warning: guest requested more bytes than allowed
processing error - resetting ehci HC
```
and the USB mouse cannot be used everywhere

**Comment by kholia** [comment]
The "resetting ehci" messages are harmless, I see them too.

The mouse problem seems to be a duplicate of https://github.com/kholia/OSX-KVM/issues/17.
