### ISSUE TITLE
No network connection in macOS 10.12.1

### ISSUE THREAD

**Issue by bialad** [kholia/OSX-KVM#30]
I'm using the boot-macOS.sh method start the machine, and installation and boot seems fine. However, I'm not getting any internet connection in the guest OS.

This is the output after boot:

```
╰─$ sudo ./boot-macOS.sh
QEMU 2.6.1 monitor - type 'help' for more information
(qemu) qemu-system-x86_64: warning: Unknown firmware file in legacy mode: genroms/multiboot.bin

ehci warning: guest requested more bytes than allowed
processing error - resetting ehci HC
ehci warning: guest requested more bytes than allowed
processing error - resetting ehci HC
ehci warning: guest requested more bytes than allowed
processing error - resetting ehci HC
```

In macOS network info it says `Ethernet has a self-assigned IP address and will not be able to connect to the internet.`

And tips for troubleshooting?

**Comment by kholia** [comment]
Follow the https://github.com/kholia/OSX-KVM/blob/master/networking-qemu-kvm-howto.txt document.

**Comment by ericsonj** [comment]
Hi I have this error:

smbus: error: Unexpected recv start condition in state 3
smbus: error: Unexpected read in state -1
smbus: error: Unexpected NACK in state -1
smbus: error: Unexpected NACK in state -1

Can you help me ?
