### ISSUE TITLE
Use tar and python (bundled with stock macOS)  for extracting pbzx stream

### ISSUE THREAD

**Issue by meeuw** [kholia/OSX-KVM#31]
Hi, you might be interested in my script for generating the iso:
https://gist.githubusercontent.com/meeuw/fb0e63c4763b3cec4ee5/raw/22a2fe2bac81f7074753fc9c79aa5b091ac05b0d/%2520generateiso.py

It only requires tar and python which are bundled with stock macOS (no external tools required for compilation etc)

**Comment by kholia** [comment]
The current "external pbzx binary file" method works fine too. Hence, I am not motivated to change it.

**Comment by kholia** [comment]
This request has been implemented now.

**Comment by meeuw** [comment]
glad to be of help 😆
