### ISSUE TITLE
Can't find boot file: 'mach_kernel'

### ISSUE THREAD

**Issue by dialed** [kholia/OSX-KVM#32]
Thank you for this. 
My system is Arch Linux, hopefully not the issue, but thought I would mention.
in both qemu and virt-manager I receive No Kernel.plist replacemnt found. Can't find boot file: 'mach_kernel' Press a key to continue...
Any help would be appreciated.
Thanks again.

**Comment by kholia** [comment]
I guess that something went wrong during the ISO creation step. Describe the steps you took to create the ISO image, and also paste the output of ISO image creator script.

**Comment by kholia** [comment]
Also see related issues,

https://github.com/kholia/OSX-KVM/issues/21
https://github.com/kholia/OSX-KVM/issues/29

**Comment by dialed** [comment]
I appreciate you getting back, and you are probably right. I will rerun this afternoon and post back. Thank you.

**Comment by dialed** [comment]
Hi kholia, you were right. I ran the the script again and everyting worked just fine. The only difference this time is that I placed the installation app in the applications directory on my mac before running without the -a option. Thank you very much!
