### ISSUE TITLE
VGA passthrough not working with q35 machine

### ISSUE THREAD

**Issue by Allexin** [kholia/OSX-KVM#35]
All works fine if we start machine with default settings from boot-macOS.sh
But works with mac OS through spice is very hard.

I am tried to launch virtual machine with VGA Passthough and failed.
If i am just add vfio:
    <qemu:arg value='-device'/>
    <qemu:arg value='vfio-pci,host=01:00.0,bus=pcie.0'/>
    <qemu:arg value='-device'/>
    <qemu:arg value='vfio-pci,host=01:00.1,bus=pcie.0'/>
nothing happens. GPU not used.

But if u change machine from q35 to i440fx - GPU starts as expected.
But mac OS image can't boot.

Any possibility to launch mac os with VGA Passthrough?

**Comment by kholia** [comment]
I have not tried VGA passthrough at all. So, you will have to debug this problem yourself.

Here are some links which might be relevant,

* https://wiki.archlinux.org/index.php/PCI_passthrough_via_OVMF
* https://gist.github.com/gordonturner/2a2e5ecde5e7860b52e2
* https://macosxvirtualmachinekvm.wordpress.com/guide-mac-os-x-10-11-el-capitan-vm-on-unraid/
* http://www.nicksherlock.com/2016/10/installing-macos-sierra-on-proxmox-4-3-qemu-2-6-1/
