### ISSUE TITLE
Anyone able to sign into imessage with this?

### ISSUE THREAD

**Issue by aaronorosen** [kholia/OSX-KVM#36]
Seems like there is some serial number check that prevents it from working? https://discussions.apple.com/thread/5673518?tstart=0

**Comment by kholia** [comment]
I believe this is a known problem.

* https://lime-technology.com/forum/index.php?topic=43816.0
* https://www.znbs.space/wordpress/?p=872

**Comment by gwigz** [comment]
There's talk about this working using the Clover bootloader, here:

-  http://www.insanelymac.com/forum/topic/309087-insanely-fast-virtual-mac-qemu-ovmf-clover-and-native-graphics/page-23

**Comment by kholia** [comment]
https://www.tonymacx86.com/threads/how-to-fix-imessage.110471/ can help but no support for this stuff is provided here.
