### ISSUE TITLE
How autostart the first selection?

### ISSUE THREAD

**Issue by voxsoftware** [kholia/OSX-KVM#39]
How I do, for autostart the first selection? Maybe after 5 seconds, defaults to first item in boot menu

**Comment by kholia** [comment]
Try removing the "CDROM" device after installation. If this doesn't work, I have no further tips.

**Comment by voxsoftware** [comment]
I don't have CDROM. In the boot have two entries: 

Macintosh HD ....
Recovery

I want to start Macintosh HD automatically, without press enter

**Comment by cro** [comment]
On the OS X disk in /Extras you can put a plist file called
'org.chameleon.boot.plist' to control Chameleon.  Details are here:

https://www.contrib.andrew.cmu.edu/~somlo/OSXKVM/

Search that page for 'org.chameleon.boot.plist'

--cro
