### ISSUE TITLE
Cannot boot on Ubuntu 16.04 Xenial

### ISSUE THREAD

**Issue by apiontek** [kholia/OSX-KVM#4]
I'm trying this on Ubuntu 16.04 Xenial, installed from beta 2 and then updated to-date, and I can't get back the enoch boot screen. I enter the text, and it seems to start booting, but then immediately reboots to the same Enoch boot screen. I've entered "-v" in front of the text and even "-f" with no luck.

With -v I see a variety of messages, but the final ones go by so quickly I don't know what they're saying. Any ideas? I'm not too familiar with any of this yet so I'm feeling pretty clueless, but I'll probably try rummaging around some hackintosh info later on to see if I can come up with solutions.

**Comment by kholia** [comment]
Type the following after boot, "KernelBooter_kexts"="Yes" "CsrActiveConfig"="103"

Did you give this a try?

**Comment by apiontek** [comment]
Sorry I wasn't more specific, but yes, that's what I meant by "I enter the text." I have tried:

`"KernelBooter_kexts"="Yes" "CsrActiveConfig"="103"`

`-v "KernelBooter_kexts"="Yes" "CsrActiveConfig"="103"`

`-v -f "KernelBooter_kexts"="Yes" "CsrActiveConfig"="103"`

**Comment by kholia** [comment]
I am quite new to the hackintosh scene. Please write back if you find a solution, thanks!

**Comment by kholia** [comment]
Try executing `echo 1 > /sys/module/kvm/parameters/ignore_msrs` on your host system.

**Comment by faddat** [comment]
@kholia Which piece of all of this did you have preexisting knowledge of?  To make such a concise guide with little hackintosh exp-- 

/me tips hat....

Nice.
