### ISSUE TITLE
Trying to connect an iPhone5s through USB

### ISSUE THREAD

**Issue by AgentBlade** [kholia/OSX-KVM#40]
First off: thanks, this tutorial was worth the time, props to you!-
--
The problem:
I click on "Add Hardware" > "USB Host Device" > iPhone5/5C/5S/6
then I apply and boot the machine, but itunes doesn't even notify its existence.
Help please, being able to connect my iPhone to macOS is the principal reason i got this far :)

**Comment by kholia** [comment]
I have not tried doing this. So you will have to debug this yourself.

Maybe [this guide](https://macosxvirtualmachinekvm.wordpress.com/guide-mac-os-x-10-11-el-capitan-vm-on-unraid/) can help.

**Comment by AgentBlade** [comment]
So i figured out what the problem is:
Apparently my cpu doesn't support pci passtrhough (you can check yours in the bios/efi/uefi settings).
The feature is called VT-d and needs to be enabled via BIOS/EFI/UEFI also you need VT-x enabled but if you (reader) got until here this isn't a problem.
Sadly I will need to buy a new computer, or upgrage by BIOS to an open source alternative and tweak it myself. Is going to be painful, but freedom's never free, right?
Anyways thanks for this tutorial, and thanks for your response.
Happy new year.
