### ISSUE TITLE
Stuck on menu Language Chooser  Indefinitely!!!

### ISSUE THREAD

**Issue by Hygens** [kholia/OSX-KVM#43]
For Sierra 10.12.2 stuck on menu Language Chooser indefinitely. Wait all time possible and nothing. On terminal showing:
QEMU 2.5.0 monitor - type 'help' for more information
(qemu) ehci warning: guest requested more bytes than allowed
processing error - resetting ehci HC
ehci warning: guest requested more bytes than allowed
processing error - resetting ehci HC
ehci warning: guest requested more bytes than allowed
processing error - resetting ehci HC

My machine is Hp Dm4t-2000 with 16Gb of memory and Linux Mint 18 with kernel 4.4.0-59.
Any idea what I do for get the menu for format HD?!

**Comment by kholia** [comment]
This issue is duplicate of issue https://github.com/kholia/OSX-KVM/issues/26.
