### ISSUE TITLE
Git history reset

### ISSUE THREAD

**Issue by z3ntu** [kholia/OSX-KVM#44]
Please don't reset the git history on every change. :)

That makes it way easier to compare for myself what changed...

**Comment by kholia** [comment]
You can always use something like "meld" to see the changes. I am not planning to maintain a Git history for this project.

**Comment by z3ntu** [comment]
Well I can't because [there is only one commit](https://github.com/kholia/OSX-KVM/commits/master).

**Comment by kholia** [comment]
You can look at various older forks of this repository. Again, I won't be maintaining history for this project.
