### ISSUE TITLE
issue when switching to graphic install

### ISSUE THREAD

**Issue by upolymorph** [kholia/OSX-KVM#46]
Hi,

I have an issue booting the installation CD.
I see the boot menu in text mode, I press enter to continue, I see soemting moving in text mode with a textual "bubble" rolling between a small o and capital O and the screen flash (sometime I see a white screen with apple really quickly) and it cycle back to the bios menu in test ... :-(

Any idea to help me?

Thanks in advance and congrats for the great job !

**Comment by kholia** [comment]
See https://github.com/kholia/OSX-KVM/blob/master/README.md#debugging.

Also see previously closed issues (https://github.com/kholia/OSX-KVM/issues) to debug this.

Once you find a solution, note it down here.

**Comment by kholia** [comment]
Which host CPU are you using? Does it have VT-x and SSE 4.1 extensions?

**Comment by upolymorph** [comment]
output of cat /proc/cpuinfo is :+1: 

processor       : 0
vendor_id       : GenuineIntel
cpu family      : 6
model           : 70
model name      : Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz
stepping        : 1
microcode       : 0x13
cpu MHz         : 3846.281
cache size      : 6144 KB
physical id     : 0
siblings        : 8
core id         : 0
cpu cores       : 4
apicid          : 0
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm epb tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid xsaveopt dtherm ida arat pln pts
bugs            :
bogomips        : 5587.11
clflush size    : 64
cache_alignment : 64
address sizes   : 39 bits physical, 48 bits virtual
power management:

so as an Intel i7 VT-x should be ebnabled and I can see that sse 4.1 and 4.2 are also enabled.

**Comment by kholia** [comment]
Have you done `echo 1 > /sys/module/kvm/parameters/ignore_msrs` on the KVM host machine? Did you generate the ISO image yourself? Which versions of OS X / macOS did you use to generate the ISO image? Which Linux distribution are you running?

**Comment by upolymorph** [comment]
`echo 1 > /sys/module/kvm/parameters/ignore_msrs` solved my current issue. sorry for disturbing for such a stupid issue. can I propose a PR with this command being part of the boot.sh or boot-MacOS.sh or there case where this command will cause issue?
Thanks for your quick help.

**Comment by kholia** [comment]
Reading documentation is important :-)

The `boot.sh` or `boot-MacOS.sh` are not typically executed with `sudo` or as root. Hence inserting `echo 1 > /sys/module/kvm/parameters/ignore_msrs` in those scripts won't work.

**Comment by upolymorph** [comment]
adding the line if [ "$(cat /sys/module/kvm/parameters/ignore_msrs)" != "Y" ]; then sudo bash -c "echo 1 > /sys/module/kvm/parameters/ignore_msrs"; fi could may do the stuff asking the password only ounce and running the other command without sudo.
Unfortunately I read the doc several time and went to the closed issues, maybe this command should be put in a requirements section on top of documentation. just willing to help. :-) Thanks again for your great work.

**Comment by kholia** [comment]
I will consider moving this debugging tip to the top of README.md in the future. Thanks.
