### ISSUE TITLE
Have you any recommedations how to build bootloader?

### ISSUE THREAD

**Issue by apatrushev** [kholia/OSX-KVM#47]
The only blob in this repo without any description is bootloader.
I have tried to rebuild it from chameleon svn without any success (osx installer crashed on first stage with unknown ACPI platform error).
Though everything is fine with provided one.
Could you please write short note on how to build it? Or may be some directions?

SVN: trunk,branches/ErmaC/Enoch
```
make distclean all
```
without any custom config

tried to use
```
sym/i386/boot
sym/i386/cdboot
```

build host: 10.11.6,xcode 8.2.1

**Comment by kholia** [comment]
I did not build `enoch_rev2839_boot` file myself. I simply extracted it from `Enoch-rev.2839.zip` (downloaded from  http://www.insanelymac.com/). The extraction steps are documented in the `notes.md` file.

I have never tried building Enoch bootloader, so I can't provide any help / support for it. Maybe https://www.contrib.andrew.cmu.edu/~somlo/OSXKVM/ can help.
