### ISSUE TITLE
no keyboard and mouse once installation gui starts.

### ISSUE THREAD

**Issue by kfirufk** [kholia/OSX-KVM#48]
Hello.
I try to install macos sierra 10.12.3 using this wonderful project.

it starts a qemu session using virt-manager. the bios boos up find, I can press return to start the macos gui installation, the problem is that once the GUI started i don't have keyboard and mouse interaction at all. 

the installation did not freeze cause the welcome text animation keeps on running. 

I checked macOS-libvirt.xml and mouse and keyboard are configured with usb bus. I have other qemu virtual machines that I run manually (without virt, but with bash script) and I don't have these kind of problems. 

any ideas ?

my system is Gentoo Linux ~amd64
Linux ufk-gentoo-work 4.9.8-gentoo #1 SMP PREEMPT Sun Feb 5 13:17:53 IST 2017 x86_64 Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz GenuineIntel GNU/Linux

with qemu version 2.8.0 and virt-manager version 1.4.0

I tried asking on IRC and they recommended me to install clover. but I didn't see any clover related information in here.

**Comment by kholia** [comment]
Try using the `boot-macOS.sh` script instead of using the libvirt method. I will check if QEMU 2.8.0 has some breaking changes.

**Comment by kholia** [comment]
I tested with QEMU 2.8.0 and it seems to be working fine.

**Comment by kfirufk** [comment]
Hi!
first of all... I wanted to create a github issue just to say thank you!! cause star is not enough! but this guy beat me to it.

ok so with boot-macOS.sh I have a mouse.. don't think I have a keyboard... pressing tabs and escape doesn't do anything. besides that, the top bar stays on 'Language Chooser' and it's actually stuck. I can't press on anything on the top bar.. I can press continue on the main installation window but that doesn't help me much cause I can't execute disk utility.

**Comment by kholia** [comment]
This stuck "Language Choose" menu bar is a known problem. See https://github.com/kholia/OSX-KVM/issues/26 for various solutions.

**Comment by kfirufk** [comment]
yes that helps. gonna install and see if it works.

donno if it's relevant but this is the output that I get from qemu.
EMU 2.8.0 monitor - type 'help' for more information
(qemu) qemu-system-x86_64: warning: Unknown firmware file in legacy mode: genroms/multiboot.bin
ehci warning: guest requested more bytes than allowed
processing error - resetting ehci HC
ehci warning: guest requested more bytes than allowed
processing error - resetting ehci HC
ehci warning: guest requested more bytes than allowed
processing error - resetting ehci HC

**Comment by kholia** [comment]
This output is "normal", so ignore. The EHCI controller exposed by QEMU doesn't work in macOS. The keyboard and mouse are attached to the UHCI controller which works fine in macOS.

**Comment by kfirufk** [comment]
yay! it works. closing. thank you!
