### ISSUE TITLE
poor graphics performance and graphics are broken on web pages in google chrome

### ISSUE THREAD

**Issue by kfirufk** [kholia/OSX-KVM#50]
Hi! :)

I noticed that I get very poor graphics performance on my MacOS installation.
I also noticed that when I browse web pages on google chrome, most of the page is white and doesn't get rendered at all (doesn't matter if it's pictures or texts). don't have this kind of problem in safari

I know that for windows I use '-vga qxl' and installed the qxl drivers which increased performance.

is there something like that for MacOS ?

using Qemu 2.8.0 on gentoo ~amd64 with MacOS Sierra 10.12.3 running with boot-macOS.sh

**Comment by kholia** [comment]
This is a known problem. See https://github.com/kholia/OSX-KVM/issues/12 for details. There is no easy solution.

**Comment by kfirufk** [comment]
I installed the usbtablet drivers from here: http://philjordan.eu/osx-virt/
and vnc works perfectly. thanks!

**Comment by kfirufk** [comment]
easily fixed audio and video using: https://www.znbs.space/wordpress/?tag=voodoohda

**Comment by kholia** [comment]
Cool.  Can you please mention the steps you took in some detail? The blog post misses the versions of the packages used, for example. It would be good to have this documented.

**Comment by kfirufk** [comment]
sure..
downloaded latest voodoohda from here: https://sourceforge.net/projects/voodoohda/ (currently v289)
and added '-soundhw hda' to boot-macOS.sh qemu parameters.

downloaded latest VMsvga2 from https://sourceforge.net/projects/vmsvga2/ (currently v1.2.5, it's no longed maintained but it works!). added "-vga vmware" to qemu parameters in boot-macOS.sh
and added 

<key>Kernel Flags</key>
<string>vmw_options_fb=0x06</string>

to  /Extra/org.chameleon.Boot.plist 

I also installed usbtablet and virtiio-network drivers from http://philjordan.eu/osx-virt/
and "-usbdevice tablet" parameter works perfectly.

**Comment by kholia** [comment]
The `VoodooHDA.kext-289.zip` is not in a `.pkg` format. To install it, did you copy the entire `VoodooHDA.kext` folder (from the zip file) into your `/System/Library/Extensions/` folder in the guest?

**Comment by kfirufk** [comment]
ahh oops I downloaded voodooHDA-2.8.8 from here: https://sourceforge.net/projects/voodoohda/files/ i'll update my post

**Comment by kholia** [comment]
Thanks! :-)

**Comment by kfirufk** [comment]
I get a black screen that doesn't go away after not pressing anything.. I think that it's just the power saving feature. gonna disable it and check if this problem occurs again. i'll post here the results.

**Comment by kfirufk** [comment]
welp.. since VoodooHDA.kext-289.zip is newer then v2.8.8, I tried installing it using kext wizard (http://www.insanelymac.com/forum/topic/253395-kext-wizard-easy-to-use-kext-installer-and-more/) and it works properly.

**Comment by kfirufk** [comment]
I failed using virtiio-network, and it was latest updated 3 years ago. I use the regular network configuration from your scripts and it works great.
