### ISSUE TITLE
macOS Sierra 10.12.3 stuck in Boot loop 

### ISSUE THREAD

**Issue by Alex-Keyes** [kholia/OSX-KVM#52]
After following the instructions in the README.md I have gotten to the point where running boot-macOS.sh gets a qemu window up and the black boot command line loads.  However, when I press enter to continue the boot, it loads, briefly flashes a white screen and then returns to the black command line bootloader.  Any idea what's causing this?

**Comment by kholia** [comment]
See https://github.com/kholia/OSX-KVM#debugging and previously closed issues. This has already been discussed numerous times.
