### ISSUE TITLE
docs: <dict> and <plist> missing

### ISSUE THREAD

**Issue by danboid** [kholia/OSX-KVM#59]
notes.md says all you need to do is create a file containing:

```
<key>Graphics Mode</key>
<string>1440x900x32</string>
```

To set the resolution but that alone doesn't work. For it to be a valid plist file it must be wrapped in at least plist and dict tags like so:

```
<plist>
<dict>
<key>Graphics Mode</key>
<string>1440x900x32</string>
</dict>
</plist>
```

Congrats on creating the easiest Hackintosh installer I've ever tried!

**Comment by danboid** [comment]
It may also be worth mentioning that /Extra doesn't exist by default on a fresh Sierra install so the user has to not only create the file but the folder too.

**Comment by Programming4life** [comment]
The file "org.chameleon.boot.plist" should already exist you would just insert the key, and the string tag. If it said "create a file containing" then I could see why the example should be changed to contain a full valid plist file, but it doesn't say to create a new file. I could be wrong, and in some cases you may need to create  the plist file but from my experience the file "org.chameleon.boot.plist" always exists.

**Comment by danboid** [comment]
Under Sierra 10.12.3, both the /Extra folder and org.chameleon.boot.plist do not exist after installation hence both need to be manually created. I would imagine this is the case for all versions of Sierra.

**Comment by kholia** [comment]
Thanks.

@Programming4life is right. `notes.md` clearly says to add the resolution information to already existing `/Extra/org.chameleon.boot.plist` file.

The "/Extra" folder has to created (copied actually) manually during the installation process as shown in the `README.md` file.

**Comment by danboid** [comment]
kholia:

I cannot see anything in the README about copying an /Extra folder. The README seems to presume the file already exists, which it does not under Sierra.

notes.md does mention /Extra after/as part of 'Kernel extraction' but I really don't understand why the user would want or need to do that? It doesn't seem to apply to a user who just wants to set the resolution. If it does, please explain how.

**Comment by Programming4life** [comment]
@danboid the `create_install_iso.sh` script should create it for you. Take a look at the script line referenced below. You'll see it's copying the `org.chameleon.boot.plist` from this repo into the `/Extra` folder.
https://github.com/kholia/OSX-KVM/blob/3fbc5813b7ad8b20f0b7f8f07cee836e08a34da4/create_install_iso.sh#L492

**Comment by chuckremes** [comment]
@danboid Additionally, look at the main README file again and you will see a bullet point that specifically tells you to copy the /Extra folder. I'll quote it so you can search for a substring on the README to find it.

"After disk initialization, open a terminal window (in the Utilities menu) and recursively copy the /Extra folder to the newly initialized target volume using bash cp -av /Extra "/Volumes/NewVolumeName" "

I know it might be a tad confusing but the information is definitely there.

**Comment by danboid** [comment]
Hi Chuck

Oh yes! I had missed that sentence - I thought I had read the entire README but I must've skimmed over that because it is amongst the screenshots.

Thanks
