### ISSUE TITLE
OSX-KVM questions

### ISSUE THREAD

**Issue by danboid** [kholia/OSX-KVM#60]
I have a few unanswered questions regarding OSX-KVM, the answers to which I would like to see added to the existing docs or maybe added to a FAQ, if there are enough to warrant creating one:

1 - I prefer to use virt-manager to manage my KVM and Xen VMs and indeed the current README recommends that the user install virt-manager. What is the correct command to import your OSX KVM image so that it can be managed using VMM / virsh etc? I think I've worked out most of it, it'd be something like this:

```
sudo virt-install --name OSX --ram 2048 --vcpus 2 --cpu Penryn,kvm=off,vendor=GenuineIntel --machine pc-q35-2.4 --disk path=/home/dan/KVM/mac_hdd.img --import --noautoconsole --force --boot kernel=enoch_rev2848_boot
```

2 - Is there any way to enable copy / paste between the OSX VM guest and a Linux host, as is possible with Windows VMs? I imagine this will require the creation of a new OSX driver for this purpose.

3 - Are there any, or are there plans to create, any PV drivers for OSX disk and/or network drivers for improved IO?

4 - Accelerated graphics? I presume the only way to achieve this is via PCI passthrough of a graphics card that is supported by macOS? It would be good if the README covered this, including recommended cards, or at least linked to a suitable guide.

Thanks for listening to my suggestions / questions!

**Comment by danboid** [comment]
It might be worth covering APFS too. It seems the Sierra installer lets you format the system drive as APFS and install to it but you cannot boot from it after doing so. I think this is a limitation of Sierra rather that KVM-OSX or its bootloader, right?

**Comment by kholia** [comment]
1. I simply edit `macOS-libvirt.xml` to point to right files before importing it using `virsh --connect`. I personally don't use `virsh` so I can't provide support for it.

2. I use SSH for terminal copy-pasting. For GUI mode, VNC might work but I haven't tried it.

3. I have no idea but I am not very hopeful. Check the corresponding upstream projects 

4.  PCI passthrough of video cards is out of scope for this project. You are on your own. No support is provided for it in any fashion whatsoever.

5. I have not idea about APFS. If it doesn't work, then simply don't use it.

Some of these might be added to a "FAQ" later on.

**Comment by kholia** [comment]
Added a note about accelerated graphics [here](https://github.com/kholia/OSX-KVM/blob/master/notes.md#accelerated-graphics).
