### ISSUE TITLE
qemu: invalid kernel header

### ISSUE THREAD

**Issue by constin** [kholia/OSX-KVM#61]
Hello i try to install this on Proxmox4.4
Before on proxmox4.3 was all great. Now i have en error:

qemu: invalid kernel header
TASK ERROR: start failed: command '/usr/bin/kvm -id 107 -chardev 'socket,id=qmp,path=/var/run/qemu-server/107.qmp,server,nowait' -mon 'chardev=qmp,mode=control' -pidfile /var/run/qemu-server/107.pid -daemonize -smbios 'type=1,uuid=5b50fd08-6a76-4141-b4c3-54f22dbfd64c' -name macos -smp '4,sockets=1,cores=4,maxcpus=4' -nodefaults -boot 'menu=on,strict=on,reboot-timeout=1000,splash=/usr/share/qemu-server/bootsplash.jpg' -vga std -vnc unix:/var/run/qemu-server/107.vnc,x509,password -cpu 'core2duo,+kvm_pv_unhalt,+kvm_pv_eoi,enforce,vendor=GenuineIntel' -m 8196 -k en-us -device 'isa-applesmc,osk=XXXXXXXXXXXXXXXXXXXXXXXXXXXX' -smbios 'type=2' -kernel /var/lib/vz/template/qemu/enoch_rev2839_boot -cpu 'core2duo,kvm=off,vendor=GenuineIntel' -readconfig /usr/share/qemu-server/pve-q35.cfg -device 'virtio-balloon-pci,id=balloon0,bus=pci.0,addr=0x3' -iscsi 'initiator-name=iqn.1993-08.org.debian:01:82b6862cc94' -drive 'file=/data/images/107/vm-107-disk-1.qcow2,if=none,id=drive-ide0,format=qcow2,cache=none,aio=native,detect-zeroes=on' -device 'ide-hd,bus=ide.0,unit=0,drive=drive-ide0,id=ide0,bootindex=100' -drive 'file=/data/template/iso/Install_OS_X_10.11_El_Capitan.iso,if=none,id=drive-ide2,format=raw,cache=none,aio=native,detect-zeroes=on' -device 'ide-hd,bus=ide.1,unit=0,drive=drive-ide2,id=ide2' -netdev 'type=tap,id=net0,ifname=tap107i0,script=/var/lib/qemu-server/pve-bridge,downscript=/var/lib/qemu-server/pve-bridgedown' -device 'e1000-82545em,mac=0E:B8:F1:FF:84:7E,netdev=net0,bus=pci.0,addr=0x12,id=net0,bootindex=300' -machine 'type=pc-q35-2.4'' failed: exit code 1

**Comment by kholia** [comment]
This project does not use Proxmox. Hence no support for it can be provided. You are on your own.

Don't report such invalid issues here.
