### ISSUE TITLE
iTunes doesn‘t recognize connected iPhone or iPad

### ISSUE THREAD

**Issue by wargblaze** [kholia/OSX-KVM#63]
Guest macOS see connected iPhone, but iTunes doesn‘t recognize device. After a while, a message appears that the connection failed.

ArchLinux, qemu 2.8.0, libvirt 3.1.0, standard kernel 4.10.3

**Comment by kholia** [comment]
See https://github.com/kholia/OSX-KVM/blob/master/notes-for-self.md for some details on this problem. In short, USB passthrough of EHCI, and XHCI (USB 3.0) devices does not work with El Capitan amd macOS Sierra guests.

I don't know how to fix this. Hence closing this bug with "cantfix" label.

**Comment by DirtyHairy** [comment]
I had the same issue and worked around it by using a USB-over-IP solution ([virtualhere](https://www.virtualhere.com/)). The full version costs money, but it works well --- I started the server on linux and was able to select and use the iPhone in the client on OSX without any further trouble (bridged networking).

**Comment by kholia** [comment]
This sounds like a neat, and very useful solution. Thanks for sharing!

**Comment by styxlab** [comment]
@DirtyHairy: With what OS X version are you using virtualhere?

I tried with macOS X 10.12.3 and it works, but with macOS X 10.12.6 it fails. Something fundamental must have changed starting from mac OS X 10.12.4. This version (and all subsequent ones, including the 10.13 betas), fail in regognizing the iphone. Other USB devices do work though.

**Comment by DirtyHairy** [comment]
@styxlab 10.12.5 works fine here. I haven't tried 10.12.6 (or the betas for that matter).

**Comment by styxlab** [comment]
That's intersting as this report [https://www.virtualhere.com/content/iphone-ios-1032-cant-be-used-os-x-10125](url) also suggests a problem with 10.12.5. Can you give some more info about your configuration?

**Comment by kholia** [comment]
I wonder if https://www.flexihub.com/download.html has the same problem.

**Comment by DirtyHairy** [comment]
> That's interesting, as this report also suggests a problem with 10.12.5. Can you give some more info about your configuration?

I guess that explains the difference: my test device is still on iOS 9 :stuck_out_tongue: Other than that, there's nothing extraordinary --- the OSX installation is pretty plain, no changes apart from VMWare video and USB tablet / HDA sound support.
