### ISSUE TITLE
Crash after 10.12.4 upgrade

### ISSUE THREAD

**Issue by th3joker** [kholia/OSX-KVM#64]
System crashes on DSMOS after upgrading from 10.12.1 to 10.12.4

![screen shot 2017-03-28 at 00 48 37](https://cloud.githubusercontent.com/assets/3340044/24382789/95abb0da-1350-11e7-9acb-c964865fde42.png)

**Comment by th3joker** [comment]
Remove the lines:
`   <qemu:arg value='-device'/>
    <qemu:arg value='isa-applesmc,osk=ourhardworkbythesewordsguardedpleasedontsteal(c)AppleComputerInc'/>`

Install FakeSMC.kext to /System/Library/Extensions and delete kextcache for workaround.

**Comment by kholia** [comment]
@th3joker Thanks!

Can you please describe how you managed to install `FakeSMC.kext` on the upgraded system which was not even booting? This would be helpful for others.

**Comment by neffs** [comment]
The "Don't steal MacOS" kext was updated in 10.12.4 and includes an additional check when receiving the OSK value. We'll probably need a qemu patch.

**Comment by th3joker** [comment]
I installed the FakeSMC.kext before applying the update, worked for me. 

Luckily I had taken a snapshot before doing the update and was able to just roll back to sort it.

Having problems with the App Store now though :-(

I'm sure there's a workaround for that so will post it once I get some time to play with it later.

**Comment by kholia** [comment]
Maybe https://github.com/kholia/OSX-KVM/blob/master/notes.md can help in resolving the App Store problems.

**Comment by kholia** [comment]
It would be great if someone can upload a copy of the new "Don't Steal MacOS" kext from a 10.12.4 system. I can try taking a look at it.

**Comment by neffs** [comment]
@kholia I sent you a mail. 

I opened it in Hopper Disassembler:
`   rax = (*(*rbx + 0x850))(rbx, 0x4f534b30, 0x20, var_70);
            if (rax != 0x0) {
                    _panic("\"DSMOS: SMC read error K0: %d\"@/BuildRoot/Library/Caches/com.apple.xbs/Sources/DontStealMacOS/DontStealMacOS-26.50.1/Dont_Steal_MacOS.cpp:191");
            }
            r14 = var_50;
            rax = (*(*rbx + 0x850))(rbx, 0x4f534b31, 0x20, r14);
            if (rax != 0x0) {
                    _panic("\"DSMOS: SMC read error K1: %d\"@/BuildRoot/Library/Caches/com.apple.xbs/Sources/DontStealMacOS/DontStealMacOS-26.50.1/Dont_Steal_MacOS.cpp:198");
            }`

The if's are new, otherwise it looks unchanged. (*rbx + 0x850) must be some read method in AppleSMC. 

Debugging enabled in qemu: 
`....
AppleSMC: READ_DATA OSK0 [27] = 0x64
AppleSMC: DATA Read b: 0 = 0x64
AppleSMC: CMD Read OSK0 B: 0
AppleSMC: READ_DATA OSK0 [28] = 0x65
AppleSMC: DATA Read b: 0 = 0x65
AppleSMC: CMD Read OSK0 B: 0
AppleSMC: READ_DATA OSK0 [29] = 0x64
AppleSMC: DATA Read b: 0 = 0x64
AppleSMC: CMD Read OSK0 B: 0
AppleSMC: READ_DATA OSK0 [30] = 0x70
AppleSMC: DATA Read b: 0 = 0x70
AppleSMC: CMD Read OSK0 B: 0
AppleSMC: READ_DATA OSK0 [31] = 0x6c
AppleSMC: EOF
AppleSMC: DATA Read b: 0 = 0x6c
AppleSMC: CMD Read OSK0 B: 0`
(reads OSK0, then stops)

Patch for qemu 2.8
https://gist.github.com/neffs/2feb3056e1c56350aebfbb5384e9c4e4

**Comment by kholia** [comment]
@gsomlo Hi, you might be interested in this topic.

**Comment by kholia** [comment]
@neffs Good analysis. I noticed the new "if statements" but I can't figure out why they are getting triggered. Currently I am leaning towards using and recommending `FakeSMC.kext` which isn't ideal.

I am now trying to figure out how to inject `FakeSMC.kext` into the generated ISO image itself.

P.S. I am not a Mac person. I created this project for cross-platform testing of my regular projects.

**Comment by th3joker** [comment]
Where does the SMBIOS info come from such as the Serial Number SOMESRLN etc

I'm trying to force it to use an SMBIOS.plist that I've made to fix the imessage and app store stuff.

**Comment by gsomlo** [comment]
On Tue, Mar 28, 2017 at 08:31:09AM -0700, Dhiru Kholia wrote:
> @gsomlo Hi, you might be interested in this topic.

OS X has been issuing warnings about AppleSMC breakage for a while now
(the bare-bones emulation currently in QEMU hasn't kept up with later
revisions and new behavior of the actual SMC on newer Mac computers).

Apparently, the 10.12.4 update finally decided to refuse to play along
with the perceived SMC "breakage". I'll try to cook up a QEMU patch to
update the emulated SMC enough to pass the new, more stringent
requirements.

I'm a bit swamped at the moment, but watch the QEMU devel mailing list
over the next several weeks -- I'll be posting something there soon,
hopefully.

Cheers,
--Gabriel

**Comment by th3joker** [comment]
The update also breaks caching server if you run MacOS Server:
```
grep INVALID_DEVICE /Library/Server/Caching/Logs/Debug.log
Request for registration from https://lcdn-registration.apple.com/lcdn/register failed: HTTP response 400, body "INVALID_DEVICE"
```

**Comment by qdel** [comment]
Hi,

Thanks all for this informations, but my vm is already crashed.

I managed to mount the partition inside my linux to add the FakeSMC.kext.

Then booted in single user on mac, and ran kextcache -u /

But it is still crashing... Do you have some information on how to rebuild kextcache in single user mode?

**Comment by kholia** [comment]
I don't have this macOS update and can't test the following steps myself.

```
cp -a FakeSMC.kext /System/Library/Extensions/
cd /System/Library/Extensions/
chmod -R 755 FakeSMC.kext
chown -R root:wheel FakeSMC.kext
rm -R /System/Library/Caches/com.apple.kext.caches
touch /System/Library/Extensions && kextcache -u /
```

Ensuring correct permissions is required. Adapt these commands to your situation.

Can you try these steps? Do they work?

**Comment by th3joker** [comment]
Copy over the FakeSMC.kext to /S/L/E then run:
`sudo chmod -R 755 /System/Library/Extensions/FakeSMC.kext; sudo chown -R root:wheel /System/Library/Extensions/FakeSMC.kext; sudo rm -R /System/Library/Caches/com.apple.kext.caches`
Then reboot that will force a kext reload. You must also remove the lines:
 `<qemu:arg value='-device'/> <qemu:arg value='isa-applesmc,osk=ourhardworkbythesewordsguardedpleasedontsteal(c)AppleComputerInc'/>`
From your virsh xml or boot-Mac.sh

**Comment by qdel** [comment]
I forgot to remove the smc device from my virsh xml. It is now working :)

I confirm that this process is able to recover a failing vm.

**Comment by kholia** [comment]
@qdel Good news! Can you please briefly describe the process to mount the macOS virtual disk image under Linux? This would be helpful for the readers. Thanks!

**Comment by qdel** [comment]
In full detail, taking a vm which started the updated and met the error during the update process (which involves reboot). (i made the mistake on 2 vm on 2 hosts xD)

First, if needed, convert your image to raw:

`$> qemu-img convert mac.qcow2 -O raw mac.raw`
Install hfsprogs, On debian linux i made:

`$> sudo apt install hfsprogs
`
Then i find the info to mount this filesystem

```
$> fdisk -l mac.raw
The backup GPT table is corrupt, but the primary appears OK, so that will be used.
Disk mac.raw: 64 GiB, 68719476736 bytes, 134217728 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: gpt
Disk identifier: 57B71968-2A56-41C6-9050-00F44DBBEB19

Device         Start       End   Sectors   Size Type
mac.raw1          40    409639    409600   200M EFI System
mac.raw2      409640 132948151 132538512  63.2G Apple HFS/HFS+
mac.raw3   132948152 134217687   1269536 619.9M Apple boot
```

On my system the '/' of mac is the second partition of ~63G. Take the 'Start' sector, and multiply it by the sector size:

```
$> echo '409640*512' | bc
209735680
```

Use this as 'offset' to configure a loop device
`$> sudo losetup -o 209735680 /dev/loop7 mac.raw`

In case of, let's try to clean a bit this filesystem. This step can be quite long
```
$> sudo fsck.hfsplus -f /dev/loop7
** /dev/loop7
** Checking HFS Plus volume.
** Checking Extents Overflow file.
** Checking Catalog file.
** Checking multi-linked files.
** Checking Catalog hierarchy.
** Checking Extended Attributes file.
** Checking volume bitmap.
** Checking volume information.
   Volume Header needs minor repair
** Repairing volume.
** Rechecking volume.
** Checking HFS Plus volume.
** Checking Extents Overflow file.
** Checking Catalog file.
** Checking multi-linked files.
** Checking Catalog hierarchy.
** Checking Extended Attributes file.
** Checking volume bitmap.
** Checking volume information.
** The volume KVM was repaired successfully.
```

If the last line is not the same.... Bad for you :/

Now we mount this filesystem

`$> mkdir macslash && sudo mount -t hfsplus -o force,rw /dev/loop7 ./macslash`

Copy the FakeSMC to the mac filesystem:

`$> sudo cp -r ~/FakeSMC.kext macslash/System/Library/Extensions`

Put rights (i have nothing in group wheel on my fs, only root:root)

```
$> sudo chown -R root:root  macslash/System/Library/Extensions/FakeSMC.kext
$> sudo chmod -R 755  macslash/System/Library/Extensions/FakeSMC.kext
```

Cleaning

`$> sudo rm -R macslash/System/Library/Caches/com.apple.kext.caches`

Unmount

`$> sudo umount macslash && sudo losetup -d /dev/loop7`


Edit the virtual machine to remove smc device /!\ Important step :) /!\
Edit the virtual machine to bind it to the raw disk if you converted it

Boot the virtual machine, the update process should restart and mac finally reboot :)

**Comment by kholia** [comment]
Thanks @qdel.

https://github.com/kholia/OSX-KVM/blob/master/notes.md now has some notes on injecting the kext into the VM disk image.

**Comment by neffs** [comment]
You can also replace "Dont Steal Mac OS X.kext" with the 10.12.3 version and recreate the kernel cache. Works fine so far.

**Comment by lzto** [comment]
fix here:

https://github.com/lzto/qemu/tree/fix-fox-macos_10_12_4

the new version of MacOS requires error mem region to be available, 
note that this is a wip path, I will clean it up and make a pull request to the upstream.

- Tong

**Comment by kholia** [comment]
@lzto  Cool! All the best in getting the patch upstreamed.

**Comment by kholia** [comment]
https://github.com/kholia/qemu/tree/macOS has the latest QEMU patches from Gabriel L. Somlo, to fix this problem.

Compiling and using latest QEMU is recommended instead of relying on the `FakeSMC.kext` method.

**Comment by rmoriz** [comment]
What fixes does `create_install_iso.sh` need to create a 10.12.4 .iso?

**Comment by kholia** [comment]
@rmoriz 

Just compile and use latest QEMU from `https://github.com/kholia/qemu/tree/macOS`.

No fixes are required for `create_install_iso.sh`. The script when run will tell you to remove a version check from it. Just do that and you should be good.

**Comment by rmoriz** [comment]
@kholia thanks. I actually did that (remove the exit line from the create_install_iso.sh), then run boot-macOS.sh with a manually build qemu (I also tried lzto's). I've also build a new a `enoch_rev2877_boot` however all I got in every case is http://i.imgur.com/hhFNhL8.png (probably PEBKAC?)

**Comment by kholia** [comment]
Have you booted an older version of macOS  Sierra successfully before? If no, see the debugging notes in `README.md` first. You could be running into some totally different issue which is unrelated to this one.

**Comment by rmoriz** [comment]
@kholia no, totally fresh installation with a blank qcow hdd. Sadly I don't have a 10.12.3 installer anymore around :(

**Comment by kholia** [comment]
http://bit.do/bootable has some older ISO images. Use them to narrow down your problem.

**Comment by gtxent** [comment]
were the patches accepted into upstream qemu yet?

**Comment by kholia** [comment]
No, see `qemu-devel` mailing list for details.

**Comment by C0rn3j** [comment]
@kholia I'm having trouble finding the thread in the mailing list that talks about this, could you please hint at the thread name/post link to it?

**Comment by fdelapena** [comment]
I had the same issue, but after replacing the enoch with `enoch_rev2877_boot` and removing the SMC stuff from the libvirt XML worked for me without issues. I use KVM from Fedora, no custom qemu build needed here.

**Comment by kholia** [comment]
Latest Enoch versions include FakeSMC in them. However, in my testing with different macOS versions it does not seems like a 100% reliable solution. Building QEMU with AppleSMC patches is still the recommended solution.

**Comment by kholia** [comment]
We now have multiple solutions for fixing this issue. Hence, I am closing this issue.

Thanks for all the help 👍

**Comment by kholia** [comment]
The AppleSMC patches have been merged in the upstream QEMU repository now 👍

**Comment by gitsnow** [comment]
I tried following the notes in this guide (https://github.com/kholia/OSX-KVM/blob/master/notes.md) as I wasn't able to boot my VM anymore.  I was able to mount the partition and copy the FakeSMC files over, but I'm still not able to boot.  I no longer get the error, but the VM just hangs at the OS X black loading screen.  The bar gets about 90% there and just get stuck.

**Comment by kholia** [comment]
The FakeSMC method is not recommended. Build latest QEMU from its upstream Git repository to solve this problem.

I have updated `notes.md` to state this explicitly.
