### ISSUE TITLE
AMD Ryzen?

### ISSUE THREAD

**Issue by tarruda** [kholia/OSX-KVM#67]
I'm interested in building a virtualization PC, and AMD's new processor is my top choice due to the excellent price/performance ratio(IMO ryzen 1700 8 cores/16 threads at 3.7 ghz for $ 330 is a steal). AFAIK emulating windows on Ryzen/KVM already works very well, including with GPU passthrough(though there are some issues with IOMMU groupings, I expect it to be fixed eventually).

But emulating OSX is also prerequisite since my work requires me to develop/test applications in all major desktop operating systems, and I have no plans of spending money on Apple products anytime soon. Considering some AMD processors have problems(according to README), do you have any information if Ryzen is supported?

**Comment by kholia** [comment]
It should work but I have no way of confirming it.

**Comment by kholia** [comment]
Here is the `cpuinfo` from openbenchmarking.org,

```
vendor_id	: AuthenticAMD
cpu family	: 23
model		: 1
model name	: AMD Ryzen 7 1800X Eight-Core Processor
stepping	: 1
microcode	: 0x8001105
cpu MHz		: 2200.000
cache size	: 512 KB
physical id	: 0
siblings	: 16
core id		: 0
cpu cores	: 8
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc extd_apicid aperfmperf pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_l2 mwaitx hw_pstate vmmcall fsgsbase bmi1 avx2 smep bmi2 rdseed adx smap clflushopt sha_ni xsaveopt xsavec xgetbv1 xsaves clzero irperf arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic overflow_recov succor smca
bugs		: fxsave_leak sysret_ss_attrs null_seg
bogomips	: 7186.18
TLB size	: 2560 4K pages
clflush size	: 64
cache_alignment	: 64
address sizes	: 48 bits physical, 48 bits virtual
power management: ts ttp tm hwpstate eff_freq_ro [13] [14]
```

**Comment by marcus-grant** [comment]
Bump. I would love to know if anyone has actually tried it. Theoretically I don't see why not, it's executing the code on the host anyhow so unless there's a missing instruction set that macOS uses it should theoretically work, but I haven't found any concrete examples yet and I'm not getting my new threadripper system until it's actually released in the next few weeks.
