### ISSUE TITLE
Boot-To-OSX is it possible?

### ISSUE THREAD

**Issue by opless** [kholia/OSX-KVM#69]
So apart from serial number issues my install is fine, running under libvirtd. (I'll look at fixing that later)

One thing that concerns me is that (re)booting drops me to the bios screen where I need to hit enter to continue to boot into OSX. 

Is there a mechanism to boot directly into OSX?

**Comment by Programming4life** [comment]
I had this issue too. You have to change the boot order in the virt-manager gui to the disk/img you have OS X installed on.
Notice how hard disk is the only item selected.
![](https://seravo.fi/wp-content/uploads/2012/02/virt-manager-winxp-options.png)

**Comment by opless** [comment]
I've just double checked the boot order, and it mirrors yours.

It still requires manual intervention even after changing values away from this, applying and back again.

**Comment by TurBoss** [comment]
I was able to fix this with chameleon

**Comment by opless** [comment]
Okay. After a fair bit of googling I seem to have figured it out...

QEMU loads the chameleon bootloader (enoch_directly, bypassing the pesky need to fiddle with MBR bootloaders, chainloading etc. that the Hackintosh folk document. This this line in virtsh:
`
    <kernel>/var/lib/libvirt/hackintosh/enoch_rev2877_boot</kernel>
`

There's no /Extra folder on my install. So I created that (as root).
`
$ sudo mkdir /Extra
`
I had downloaded Champlist, via a round-about way from [tools.inmac.org](https://web-beta.archive.org/web/20170107041511/http://tools.inmac.org) via archive.org

After adding a 10 sec timeout and "Save As" the appropriate plist file in /Extra 

file: /Extra/org.chameleon.Boot.plist
`
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
        <key>Credits</key>
        <string>Created with Champlist</string>
        <key>Timeout</key>
        <string>10</string>
</dict>
</plist>
`

One quick reboot later and I'm auto-booting into Sierra like a champ!
