### ISSUE TITLE
how enable autostart 

### ISSUE THREAD

**Issue by mazankod** [kholia/OSX-KVM#70]
Hello.
Thank you for your project.
I use enoch_rev2877_boot from your project.
Every time when i startup my MacOS, it ask me choose volume. How can i solve it? And how can i edit already existing enoch_rev2877_boot add timeout or Quiet Boot?

**Comment by kholia** [comment]
Do not create duplicate bugs. See https://github.com/kholia/OSX-KVM/issues/69.
