### ISSUE TITLE
GPU Paththrough issue

### ISSUE THREAD

**Issue by arkan** [kholia/OSX-KVM#71]
Hello there,

First of all, thanks for the project. I've been able to quickly install OSX on my unRaid server. 

However I'm not able to attach my NVIDIA GPU to the VM, and I'm wondering if this is somehow related to enoch? 

I reused the statement used by another windows working VM where the GPU is used when I want to play. 

I added 
```
    <hostdev mode='subsystem' type='pci' managed='yes'>
      <driver name='vfio'/>
      <source>
        <address domain='0x0000' bus='0x01' slot='0x00' function='0x0'/>
      </source>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x06' function='0x0'/>
    </hostdev>
```
However the screen remains black and the VM doesn't seem to start (doesn't join the network). 

And here is the complete manifest:
```
<domain type='kvm' id='32' xmlns:qemu='http://libvirt.org/schemas/domain/qemu/1.0'>
  <name>OSX</name>
  <uuid>0ba39646-7ba1-4d41-9602-e2969a3fc26d</uuid>
  <metadata/>
  <memory unit='KiB'>4194304</memory>
  <currentMemory unit='KiB'>4194304</currentMemory>
  <vcpu placement='static'>6</vcpu>
  <cputune>
    <vcpupin vcpu='0' cpuset='2'/>
    <vcpupin vcpu='1' cpuset='3'/>
    <vcpupin vcpu='2' cpuset='4'/>
    <vcpupin vcpu='3' cpuset='5'/>
    <vcpupin vcpu='4' cpuset='6'/>
    <vcpupin vcpu='5' cpuset='7'/>
  </cputune>
  <resource>
    <partition>/machine</partition>
  </resource>
  <os>
    <type arch='x86_64' machine='pc-q35-2.7'>hvm</type>
    <kernel>/mnt/disks/Samsung_SSD_850_EVO_250GB_S2R6NX0H750197X/OSX/OSX-KVM/enoch_rev2877_boot</kernel>
    <boot dev='cdrom'/>
    <bootmenu enable='yes'/>
  </os>
  <features>
    <acpi/>
  </features>
  <cpu mode='custom' match='exact'>
    <model fallback='forbid'>Penryn</model>
  </cpu>
  <clock offset='utc'/>
  <on_poweroff>destroy</on_poweroff>
  <on_reboot>restart</on_reboot>
  <on_crash>destroy</on_crash>
  <devices>
    <emulator>/usr/bin/qemu-system-x86_64</emulator>
    <disk type='file' device='disk'>
      <driver name='qemu' type='raw'/>
      <source file='/mnt/disks/Samsung_SSD_850_EVO_250GB_S2R6NX0H750197X/OSX/vdisk1.img'/>
      <backingStore/>
      <target dev='hda' bus='sata'/>
      <alias name='sata0-0-0'/>
      <address type='drive' controller='0' bus='0' target='0' unit='0'/>
    </disk>
    <controller type='usb' index='0' model='piix3-uhci'>
      <alias name='usb'/>
      <address type='pci' domain='0x0000' bus='0x02' slot='0x01' function='0x0'/>
    </controller>
    <controller type='sata' index='0'>
      <alias name='ide'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x1f' function='0x2'/>
    </controller>
    <controller type='pci' index='0' model='pcie-root'>
      <alias name='pcie.0'/>
    </controller>
    <controller type='pci' index='1' model='dmi-to-pci-bridge'>
      <model name='i82801b11-bridge'/>
      <alias name='pci.1'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x1e' function='0x0'/>
    </controller>
    <controller type='pci' index='2' model='pci-bridge'>
      <model name='pci-bridge'/>
      <target chassisNr='2'/>
      <alias name='pci.2'/>
      <address type='pci' domain='0x0000' bus='0x01' slot='0x01' function='0x0'/>
    </controller>
    <interface type='bridge'>
      <mac address='52:54:00:00:20:20'/>
      <source bridge='br0'/>
      <target dev='vnet0'/>
      <model type='e1000-82545em'/>
      <alias name='net0'/>
      <address type='pci' domain='0x0000' bus='0x02' slot='0x03' function='0x0'/>
    </interface>
    <input type='mouse' bus='ps2'>
      <alias name='input0'/>
    </input>
    <input type='keyboard' bus='ps2'>
      <alias name='input1'/>
    </input>
    <hostdev mode='subsystem' type='pci' managed='yes'>
      <driver name='vfio'/>
      <source>
        <address domain='0x0000' bus='0x01' slot='0x00' function='0x0'/>
      </source>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x06' function='0x0'/>
    </hostdev>
    <memballoon model='none'>
      <alias name='balloon0'/>
    </memballoon>
  </devices>
  <seclabel type='none' model='none'/>
  <seclabel type='dynamic' model='dac' relabel='yes'>
    <label>+0:+100</label>
    <imagelabel>+0:+100</imagelabel>
  </seclabel>
  <qemu:commandline>
    <qemu:arg value='-device'/>
    <qemu:arg value='usb-kbd'/>
    <qemu:arg value='-device'/>
    <qemu:arg value='usb-mouse'/>
    <qemu:arg value='-smbios'/>
    <qemu:arg value='type=2'/>
    <qemu:arg value='-device'/>
    <qemu:arg value='isa-applesmc,osk=TRUNCATED'/>
    <qemu:arg value='-device'/>
    <qemu:arg value='ide-drive,bus=ide.1,drive=MacDVD'/>
    <qemu:arg value='-drive'/>
    <qemu:arg value='id=MacDVD,if=none,snapshot=on,file=/mnt/user/ISOS/Install_macOS_Sierra_OS_X_10.12.iso'/>
  </qemu:commandline>
</domain>
```

Any idea? Thanks :)

**Comment by kholia** [comment]
The `notes.md` file clearly says `GPU passthrough is out of scope for this project. No support for it is provided whatsoever`.

**Comment by kyledayton** [comment]
@arkan, I was able to get GPU passthrough working successfully. I have written up some instructions which may help:

# OSX-KVM w/ GPU Passthrough (Nvidia)

## Overview

This guide makes a few assumptions:

* Your hardware supports VT-d
* Your hardware supports IOMMU isolation (either natively or with the ACS override kernel patches)
* You already have your passthrough PCIe device(s) isolated with vfio-pci
* You have installed the TianoCore/OVMF UEFI Bios firmware

I'm using the following hardware, these instructions may or may not work with your particular setup:

* Intel i7-4790k
* MSI Z97 Gaming5
* MSI GTX 1080

To begin, follow the instructions in this repo and make sure you have a working VM installation. I'm using Sierra 10.12.5, which required some [patches for QEMU](http://www.contrib.andrew.cmu.edu/~somlo/OSXKVM/) to work correctly.

## Setup

Inside your VM, download the following files:

* [Clover Bootloader w/ QEMU patches](http://s3.nicksherlock.com/forumposts/2016/Clover_v2.4k_r4061_edk2_r24132_qemu_patch.pkg)
* [Clover config.plist](http://s3.nicksherlock.com/forumposts/2016/config.plist)
* [q35-acpi-dsdt.aml](http://s3.nicksherlock.com/forumposts/2016/q35-acpi-dsdt.aml)
* [Nvidia WebDriver 378.05.05](https://images.nvidia.com/mac/pkg/378/WebDriver-378.05.05.15f01.pkg)

Start by installing the Clover bootloader:

* Launch the Clover bootloader installer
* After selecting your disk to install to, select `Customize`
* Select `Install for UEFI booting only`
* Under `Drivers64UEFU`, select `OsxAptioFix2Drv-64` and `PartitionDxe-64`
* Finish Installation

The Clover installer should have left an EFI volume mounted. Copy and overwrite `EFI/CLOVER/config.plist` with the downloaded one. Copy the downloaded `q35-acpi-dsdt.aml` file into `EFI/CLOVER/ACPI/origin`

Next, onstall the Nvidia drivers, then and select `Restart` when the installation is finished. Power off the VM.

Edit the VM's libvirt configuration:

```
# virsh edit <OSX_DOMAIN_NAME>
```

Under `os`, remove the `kernel` line and add:

```
<loader readonly='yes' type='pflash'>/path/to/OVMF_CODE.fd</loader>
```

Under `qemu:commandline`, remove the lines for the installation DVD (if not done as part of your initial install), as well as the `-usb` line, and lines for the usb mouse/keyboard.

Save the configuration.

Inside of libvirt, remove the `Display VNC` and `Video VMVGA` hardware, add your PCIe Devices, USB devices, and change the model of the USB controller to `USB 2`.

Boot the VM. If all went well, the display connected to your passthrough PCIe device should turn on, and you should be greeted with the Clover boot screen. Using the keyboard, navigate to `Options -> Graphics Injector`, and enable `Use NVIDIA Web Driver`, then boot macOS.

**Comment by markmcwong** [comment]
hey thank you for your detail guide :) my second gpu has got the display output and show clover menu but my keyboard (and mouse) is not working

Here is my xml config for libvirt - I understand that the boot-MacOS.sh is a better option but I would like to use my GPU also eventhough I know its not supported I want some help of why the keyboard is not working :)
[OSX-KVM.xml](https://gist.githubusecontent.com/markmcwong/14f02a9f0ce5f96e65e15fcb62b7b63b/raw/c04ce0eaf3fab67b062c20d515cfd51b43ad79fe/OSX-KVM.xml)

I deleted all the usb keyboard and mouse and `device` in `<qemu:commandline>`, however when I try to delete 
`<input type='mouse' bus='ps2'/>
<input type='keyboard' bus='ps2'/>`

then define the xml with virsh : 
`sudo virsh define /etc/libvirt/qemu/OSX-KVM.xml`
they appear again

I also added my usb keyboard with the option of add hardware and change the USB controller to `USB 2` then I also tried `default` but doesnt work

And I am quite sure the keyboard is working as I am using it now and hackintosh before

**Comment by kyledayton** [comment]
@markmcwong I see your domain configuration is missing these lines: https://github.com/kholia/OSX-KVM/blob/master/macOS-libvirt.xml#L52-L53, maybe that will help.

I noticed that your keyboard is a Razer, which might have issues without the proper drivers. Maybe you have a basic USB keyboard you can try?

Also, please post your specs (Host OS/Version, QEMU/Libvirt version, OSX version, Motherboard Model, etc..) so I can better assist

**Comment by markmcwong** [comment]
@kyledayton thank you for your reply

I was trying to boot with those two lines:
`    <qemu:arg value='-device'/>
    <qemu:arg value='isa-applesmc,osk=ourhardworkbythesewordsguardedpleasedontsteal(c)AppleComputerInc'/>`

But I got kernel panic
Therefore I removed the line as https://github.com/kholia/OSX-KVM/issues/64 mentioned

And I have MacOS Sierra 10.12.4, Manjaro, Gigabyte H110M-S2HP motherboard which can use VT-d with i7-6700k, I will check my libvirt version and with a basic usb keyboard

Just wondering how do you know i have a razer keyboard lol

**Comment by markmcwong** [comment]
running `virsh version` in terminal

`Compiled against library: libvirt 3.3.0
Using library: libvirt 3.3.0
Using API: QEMU 3.3.0
Running hypervisor: QEMU 2.9.0`

**Comment by markmcwong** [comment]
Do you mind if you can post your xml config so I can see if I misunderstand your instructions or miss out anything?

**Comment by markmcwong** [comment]
I got it work finally!

I was comparing my win10 VM xml with my MacOS and I did some Googling, mess around and add back
video QXL and Display Spice to my VM - as I read the article from:
https://askubuntu.com/questions/769108/xrdpxfce-to-install-virtual-machines-in-kvm-keyboard-does-not-work

And now my GTX970 can output signal for my macOS!

If anyone want to check out my XML
https://gist.github.com/markmcwong/530563066fdfea9de73d1fa2a065afc5

**Comment by tilllt** [comment]
Elsewhere it mentiones you have to blacklist the gfx cards (you want to pass through to the guest)  so the Host system does not grab them for itself, how did you guys prevent that?

**Comment by markmcwong** [comment]
so to prevent/blacklist the cards we assign pci-stub or vfio-pci driver to isolate the gpu -(gpu as a pci-device) - so that the graphic cards does not use nvidia/amd/intel driver but a driver that allows us to passthrough

here is a go-to / must read guide for gpu passthrough for linux 
https://wiki.archlinux.org/index.php/PCI_passthrough_via_OVMF

It is specifically for arch linux but the concept behind probably gives you a better idea - i suggest you can google or search on reddit "gpu passthrough *for your linux distro*"

I am not an expert but i hope that helps :)

**Comment by tilllt** [comment]
Thanks for the answer. Another question, just to clarify: I cannot find any explanation why to use a patched clover bootloader instead of the Enoch bootloader mentioned in kholia's write-up. What's the idea behind using clover instead of Enoch, to load your board specific DSDT's? And what are these patches to clover exactly doing and are they still needed?

**Comment by tilllt** [comment]
And another question, on your machine how do benchmark scores between virtualized osx and direct osx compete?

**Comment by kyledayton** [comment]
@tilllt AFAIK, Enoch bootloader is a legacy BIOS which tricks the OS into thinking it's an EFI machine. Clover is a true uEFI BIOS which is necessary to support VGA passthrough. The patches to clover are necessary because of a bug in clover/QEMU which causes the wrong CPU speed to be detected, resulting in the system running too fast or too slow. More information on the issue and instructions on building clover w/ patches yourself can be found [here](http://www.nicksherlock.com/2016/11/using-clover-uefi-boot-with-sierra-on-proxmox/)

While I don't have a real mac with similar specs, compared to all of the MBPs / iMacs I've used, I'd say the VM setup actually works better. I'm able to achieve near-native speeds when using ShaderToy, video decoding is smooth, and everything feels quite snappy. Probably the best "Mac" I've ever used.

**Comment by tilllt** [comment]
Ok, and more questions... I recently stumbled upon the existence of Intels GVT GPU Virtualization. As far as i understand they have a patched KVM-QEMU that exposes a Intel GFX Card to the VM which can be shared between the Host and the VM. 

https://github.com/01org/gvt-linux/wiki/GVTg_Setup_Guide

Also, it sounds as if the Guest will detect Intel Graphics, so it doesnt need special patched GFX Drivers. Did anyone have success going that route instead  of passing through the entire GPU to the guest? For me it would be especially interesting since i am trying to figure out a way to use PC Notebook with NVidia Optimus as the machine running OSX-KVM, with the goal of doing multimedia work in the guest system...
