### ISSUE TITLE
How to get a supported OS X image

### ISSUE THREAD

**Issue by kalsan** [kholia/OSX-KVM#72]
The script claims that it dosn't support Sierra .4 and higher. However, Apple only allows the download of the most recent version.

Is there a legal way to get an older version of OS X? If not, is there any chance that you will update the iso creator?

**Comment by kholia** [comment]
Remove the version check from the script manually. It should work fine if you are using latest patched QEMU (see the open issue about 10.12.4 booting problem).

**Comment by kalsan** [comment]
Thanks! In case any one else arrives here, the issue is #64 

I'm on Arch Linux and I'm not in a hurry so I'll probably just patiently wait for the new qemu release :-)
