### ISSUE TITLE
"Script is designed to be run only with bash" message in bash.

### ISSUE THREAD

**Issue by mpope9** [kholia/OSX-KVM#74]
I am running bash and get the error message "Script is designed to be run only with bash".  Running the command: `ps -o comm -p $$ | tail -n1 2>/dev/null` as found in the script returns 'bash'.

**Comment by kholia** [comment]
You report is lacking important details.

Which host OS are you running this script under? It needs to be run on macOS Sierra under bash.

What happens when you disable or patch this check from the script? Does the script work fine then?
