### ISSUE TITLE
Maximum host CPU usage

### ISSUE THREAD

**Issue by PeterSurda** [kholia/OSX-KVM#75]
First of all, thank you very much for this project, thanks to it I finally managed to run OSX in libvirt, allowing me to easier test and make OSX builds.

Now to my actual issue, which is admittedly a minor one. I have a 10.7.5 (guest) on Ubuntu 17.04 (host). qemu for this guest uses all the hosts' allocated CPU. If I assign it 4 threads (or 4 cores, has the same effect), `top` shows it consumes 400% (approximately, it fluctuates around the 400%). The other VMs (windows, linux, bsd) don't do this. Is this expected, can I do something about it?

The second, an even smaller, issue, is that after doing a suspend & resume, the clock doesn't update itself, I have to manually do a `ntpdate`. Can I work around that somehow?

**Comment by kholia** [comment]
The 400% CPU usage is not normal. Look inside the guest VM to see what might be causing this high CPU usage. Are you really running Mac OS X Lion (10.7.5) in the VM? This version was never tested and is not supported. Try running 10.11.6 or 10.12.5 (macOS Sierra) instead.

For the second issue, I guess that you will have to continue running `ntpdate`.

**Comment by PeterSurda** [comment]
Thank you. Can I email you if I have more questions, or are you reachable by some other means (e.g. IRC)?

**Comment by kholia** [comment]
I have very limited free time, so I cannot provide any end-user support. All I know is already documented in this repository.

Thanks for understanding.
