### ISSUE TITLE
DSMOS: SMC read error K0: 133

### ISSUE THREAD

**Issue by vazquc** [kholia/OSX-KVM#77]
Hello Guys;
I found this forum with same error that I am facing, I don't know if my question fit here but maybe you can give me a hint.
Thank you in advance

I was running without issues OS Sierra (10.12) on VMware Workstation 12 pro, after upgrade VMware Workstation I tried to power on the VM and got the error "DSMOS: SMC read error K0: 133"@/BuildRoot/Library/Caches/com.apple.xbs/Sources/DontStealMacOS/DontStealMacOS-26.50/Dont_Steal_MacOS.cpp:191
 

Any Ideas?

![osmac issue](https://user-images.githubusercontent.com/29713182/27552543-6cc2d40a-5a6d-11e7-9173-0d7278ac1e64.PNG)

**Comment by kholia** [comment]
This project does not use or recommend VMware Workstation. I don't understand why you have created this invalid issue at all.

General Note: Read documentation carefully (including closed issues) and do not create duplicate issues.
