### ISSUE TITLE
IDE Speed Issue

### ISSUE THREAD

**Issue by jasonbrianhall** [kholia/OSX-KVM#78]
Since Mac OS X doesn't support Virtual IO, I found out the fastest way to install Mac OS X when using /var/lib/libvirt/images as an SSD with an XFS is to mount the drive with these options during the install.

mount /var/lib/libvirt/images -o remount,inode64,noatime,nodiratime,discard,ikeep,nobarrier

My install time went from 8 hours to about 3 minutes.

**Comment by kholia** [comment]
Thanks for the tip. I use `ext4` which works OK without any tweaking. Maybe some of these mount options can benefit `ext4` users too.
