### ISSUE TITLE
Clover video corruption

### ISSUE THREAD

**Issue by cawilliamson** [kholia/OSX-KVM#80]
I've got a very strange issue at the moment.

I've completed the macOS install, got everything working perfectly. I'm now in the process of switching to Clover as my bootloader and have two strange issues:

1.) When vmvga is selected as the video output mode - absolutely nothing is displayed out at all.

2.) When vga is selected as the video output Clover looks great (yay!) but when you actually select a boot option the screen is completely messed up. The issues start when the progress bar is loaded in - the bar is replicated across the screen around 7 times and once the boot is complete and macOS actually starts up - the display is about 1/2 the normal height and the image is replicated again around 7 times overlapping eachother.

Screenshot of what I mean:
https://www.dropbox.com/s/cpt6o6irzq4flrg/Screen%20Shot%202017-07-23%20at%2020.53.40.png?dl=0

Strangely this issue ONLY occurs with UEFI/Clover. When booting via the standard included bootloader it looks just great.

Has anyone seen this issue before and can provide any guidance?

Thanks!

**Comment by kholia** [comment]
No support is provided for OVMF and Clover based installations at the moment.

I think that the Clover resolution is being set to an unsupported value.

**Comment by cawilliamson** [comment]
If no support is provided for it - why are the files in your repo?

That sends a very mixed (and annoying as f**k) message!

**Comment by kholia** [comment]
https://github.com/kholia/OSX-KVM/blob/master/UEFI/README.md clearly states,

```No support is provided for OVMF and Clover based installations at the moment. Experiment at your own risk.```

Read the documentation carefully, and try to understand it. This part is in development, and I need to learn it before I can provide support.

@cawilliamson Does this make sense to you now?
