### ISSUE TITLE
Circular dependency for getting the ISO

### ISSUE THREAD

**Issue by hobarrera** [kholia/OSX-KVM#9]
There's kind of a circular dependency in order to grab the ISO.

To run the Apple App Store, I need to install the OS, and for this, I need to run the Apple App Store.

Is there some way of fetching the ISO form the recovery boot mode (booting with cmd+r)?

**Comment by timotei** [comment]
AFAIK you can install (first) OS X via the recovery partition, by booting with `cmd + opt + r`.

**Comment by hobarrera** [comment]
> AFAIK you can install (first) OS X via the recovery partition, by booting with cmd + opt + r.

My intention is to install OS X on a VM, not on a physical machine.

**Comment by kholia** [comment]
http://bit.do/bootable has some prebuilt ISO images to get things started.
